dependencies:
  flutter:
    sdk: flutter
  
  # Dependencies yang diperlukan:
  http: ^0.13.6 # Untuk komunikasi Apps Script (doGet/doPost)
  provider: ^6.1.1 # Untuk state management
  shared_preferences: ^2.2.2 # Untuk menyimpan user aktif
  # Tambahkan path gambar jika Anda menggunakannya, misal:
  # assets:
  #   - assets/depo.png
